# Generated by Django 5.0.3 on 2024-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
