# Generated by Django 5.0.3 on 2024-03-20 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal value')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='interest_rate')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('bank', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
