# Generated by Django 5.0.3 on 2024-03-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
