# Generated by Django 5.0.3 on 2024-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_maturity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
